# Generated by Django 5.0 on 2023-12-24 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 15, 9, 51, 851085, tzinfo=datetime.timezone.utc)),
        ),
    ]
