# Generated by Django 5.0 on 2024-01-08 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 12, 50, 29, 826588, tzinfo=datetime.timezone.utc)),
        ),
    ]
