# Generated by Django 5.0 on 2024-01-08 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 12, 51, 23, 326196, tzinfo=datetime.timezone.utc)),
        ),
    ]
