# Generated by Django 5.0 on 2024-01-12 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 4, 41, 2, 278409, tzinfo=datetime.timezone.utc)),
        ),
    ]
