# Generated by Django 5.0 on 2023-12-25 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 11, 34, 54, 126468, tzinfo=datetime.timezone.utc)),
        ),
    ]
