# Generated by Django 5.0 on 2024-01-12 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_picture_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 5, 28, 11, 562383, tzinfo=datetime.timezone.utc)),
        ),
    ]
