# Generated by Django 5.0 on 2024-01-12 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 16, 27, 10, 154058, tzinfo=datetime.timezone.utc)),
        ),
    ]
