# Generated by Django 5.0 on 2023-12-26 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_category_price_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 8, 33, 23, 288071, tzinfo=datetime.timezone.utc)),
        ),
    ]
