# Generated by Django 5.0 on 2023-12-28 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_rent_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 2, 37, 32, 559445, tzinfo=datetime.timezone.utc)),
        ),
    ]
