# Generated by Django 5.0 on 2024-02-15 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_category_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 6, 22, 1, 615439, tzinfo=datetime.timezone.utc)),
        ),
    ]
