# Generated by Django 5.0 on 2023-12-24 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_rent_end_date'),
        ('users', '0002_rename_extenteduser_myuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='ExtendedUser',
        ),
    ]
