# Generated by Django 5.0 on 2023-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_extendeduser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
